config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :videos
  root to: 'videos#index' #Topページをindexに
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/video.rb
class Video < ApplicationRecord

	validates :url, presence:true #何も入力されてなければエラー表示(presence)
	validates :description, presence: true,
													length: { in: 6..140}#文字数6字から140字の間ならOK

	default_scope -> { order(created_at: :desc) } #記事の順番を作成日順に並べる/descはdescendingの略で降順の意味

	def iframe_url
		org = read_attribute(:url) 
		org.gsub("watch?v=", "embed/" ) if org.present? #watchをembedに変換(URLをiframe用に変換)
	end

	def thumbnail_youtube
		"http://i.ytimg.com/vi/#{youtubeId}/mqdefault.jpg"#サムネイル表示用のurl
	end

	def youtubeId
		# https://www.youtube.com/watch?v=n-zTeG1YsGM #urlの例
		md = url.match(/watch\?v\=(.*)/) #urlからIdのみを取り出す
		md[1] if md.present?
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
  class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :authenticate_user!, only: :new # ユーザがログインしていないと"new"にアクセスできない
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all.page(params[:page])
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: '動画の投稿に成功しました！' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: '動画の更新に成功しました！' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: '動画を削除しました！' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:url, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
  	<meta charset="UTF-8">
    <title>TestVideoApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <%= breadcrumbs separator: "　>　" %>
  	<header class="navbar">
		  <div class="container">
		    <div id="logo"><%= link_to "Fany", videos_path %>
		    	<div class="logo_under">笑う動画SNS</div>
		    </div>
		    <% if user_signed_in? %>
		    <!-- ログイン時ヘッダーの表示 -->
			    <ul class="header-right">
			      <li><%= link_to "動画一覧", videos_path %></li>
			      <li><%= link_to "投稿する", new_video_path %></li>
			      <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
			      <div class="fb-like fb" data-href="<%= "http://#{request.host+request.fullpath}" %>" data-send="false" data-layout="button_count" data-width="450" data-show-faces="false"></div>
			    </ul>
			  <% else %>
			  	<ul class="header-right"> 
			  	<!-- ログインしてない時ヘッダーの表示 -->
			      <li><%= link_to "動画一覧", videos_path %></li>
			      <li><%= link_to "投稿する", new_video_path %></li>
			      <li><%= link_to "ログイン", new_user_session_path %></li>
			      <div class="fb-like fb" data-href="<%= "http://#{request.host+request.fullpath}" %>" data-send="false" data-layout="button_count" data-width="450" data-show-faces="false"></div>
			    </ul>
			  <% end %>
		  </div>
		</header>
		<div class="container">
			<div class="container">
				<p><%= notice %></p> <!-- ログイン成功メッセージ -->
			</div>
			<p><%= alert %></p> <!-- ログインしてくださいメッセージ -->
   		<%= yield %>
		</div>
		<footer>
			<div class="container">
				<div class="corporate_info">
		    	<ul>
			      <li><a href="#">運営会社</a></li>
			      <li><a href="#">利用規約</a></li>
			      <li><a href="#">プライバシーポリシー</a></li>
			      <li><a href="#">お問合せ</a></li>
		    	</ul>
	    		<p>©Fany ALL RIGHTS RESERVED.</p>
	  		</div>
  		</div>
		</footer>
		<div id="fb-root"></div>
<script>(function(d, s, id) {
	  var js, fjs = d.getElementsByTagName(s)[0];
	  if (d.getElementById(id)) return;
	  js = d.createElement(s); js.id = id;
	  js.src = "//connect.facebook.net/ja_JP/sdk.js#xfbml=1&version=v2.8";
	  fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));
</script>
  </body>
</html>

app/views/videos/_form.html.erb
<%= form_for(video) do |f| %>
  <% if video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(video.errors.count, "error") %></h2>

      <ul>
      <% video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="container">
  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url, :placeholder => "(例)https://www.youtube.com/watch?v=CdXesX6mYUE"%>
  </div>

  <div class="field content-field">
    <%= f.label :description %>
    <%= f.text_area :description, :maxlength => "120", :placeholder => "動画の説明など伝えたいことを書いてみよう！"%>
  </div>

  <div class="actions primary-btn btn2">
    <%= f.submit :value => "投稿する"%>
  </div>
</div>  
<% end %>

app/views/videos/edit.html.erb
<% breadcrumb :video, @video %>
<div class="container">
	<h1>編集</h1>

	<%= render 'form', video: @video %>

	<%= link_to 'Show', @video %> |
	<%= link_to 'Back', videos_path %>
</div>

app/views/videos/index.html.erb
  <% breadcrumb :root %>
  <div class="contents">
    <ul class="main-contents">
      <% @videos.each do |video| %>
        <%= link_to video_path(video) do %><!-- showへのリンク -->
          <li>
            <div class="thumbnail2 img-responsive videoBox">
              <%= image_tag video.thumbnail_youtube %><!-- サムネイル表示 -->
              <img src="/assets/media-play-key.png" class="play img-responsive">
            </div>
            <p><%= video.description %></p>
            <!--<%= link_to '詳細 |', video %>
            <%= link_to '編集 |', edit_video_path(video) %>
            <%= link_to '削除', video, method: :delete, data: { confirm: '本当に削除しますか？' } %> -->
          </li>
        <% end %>
      <% end %>
    </ul>
    <!-- <div class="side-contents">
      <div class="ad-area">
        <img src="/assets/datumou_design_sample.jpg" alt="">
        <p>広告</p>
      </div>
      <div class="popular-videos">
        人気の動画
      </div>
    </div> -->
  </div>
  <%= paginate @videos %>
 <!--<%= link_to '投稿する！！！', new_video_path %> -->

app/views/videos/new.html.erb
<% breadcrumb :new %>
<div class="container">
	<h1 class="newh1">Youtube動画を投稿する</h1>

	<%= render 'form', video: @video %>

	<%= link_to '戻る', videos_path %>
</div>

app/views/videos/show.html.erb
<div class="container">
	<% breadcrumb :video, @video %>
	<div class="youtube">
		<iframe src="<%= @video.iframe_url %>" frameborder="0" allowfullscreen></iframe>
	</div>
	<div class="show-content">
		<h1><%= @video.description %></h1>
	</div>
	 
	<p id="notice"><%= notice %></p>

	<%= link_to '編集する', edit_video_path(@video) %> |
	<%= link_to '削除する', @video, method: :delete, data: { confirm: '本当に削除しますか？' } %> |
	<%= link_to '戻る', videos_path %>
</div>